CREATE DATABASE library_management;
USE library_management;

/*Hey bro*/
CREATE TABLE STUDENT (
	Student_ID VARCHAR(20) PRIMARY KEY,
    Pin CHAR(4) NOT NULL,
    Fname VARCHAR(50) NOT NULL,
    Lname VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Phone VARCHAR(15) NULL
    );

CREATE TABLE CLASS (
	Class_ID INT PRIMARY KEY AUTO_INCREMENT,
	Department VARCHAR(50) NOT NULL,
    Number VARCHAR(10) NOT NULL,
    Semester VARCHAR(20) NOT NULL,
    Section VARCHAR(10) NOT NULL
    );
    ALTER TABLE CLASS
	ADD COLUMN Class_title VARCHAR(150) NOT NULL;

CREATE TABLE BOOK (
	ISBN VARCHAR(13) PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Description VARCHAR(3500) NOT NULL
    );

CREATE TABLE LOCATION (
	Location_ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Street VARCHAR(100) NOT NULL,
    City VARCHAR(50) NOT NULL,
    State CHAR(2) NOT NULL,
    ZIP VARCHAR(10) NOT NULL
    );
    
CREATE TABLE FORMAT (
	Location_ID INT,
    ISBN VARCHAR(13),
    Format_type VARCHAR(20),
    Quantity INT NOT NULL DEFAULT 0,
    PRIMARY KEY (Location_ID, ISBN, Format_type),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (Location_ID) REFERENCES LOCATION(Location_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CHECK (Format_type IN ('Hardcopy', 'E-Book')),
    CHECK (Quantity >= 0)
    );
    
CREATE TABLE BOOK_AUTHOR (
	ISBN VARCHAR(13),
    Author VARCHAR(100),
    PRIMARY KEY(ISBN, Author),
    FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
		ON DELETE CASCADE
        ON UPDATE CASCADE
	);

CREATE TABLE BOOK_GENRE (
	ISBN VARCHAR(13),
    Genre VARCHAR(50),
    PRIMARY KEY (ISBN, Genre),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	);

CREATE TABLE BORROWS (
	Student_ID VARCHAR(20),
	Location_ID INT,
    ISBN VARCHAR(13),
    Format_type VARCHAR(20),
    Checkout_date DATE,
    Due_date DATE GENERATED ALWAYS AS (DATE_ADD(Checkout_date, INTERVAL 14 DAY)) STORED,
	PRIMARY KEY (Student_ID, Location_ID, ISBN, Format_type, Checkout_date),
    FOREIGN KEY (Location_ID) REFERENCES LOCATION(Location_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (Location_ID, ISBN, Format_type) REFERENCES FORMAT(Location_ID, ISBN, Format_type)
		ON DELETE CASCADE
        ON UPDATE CASCADE
    );

CREATE TABLE TAKES (
	Student_ID VARCHAR(20),
    Class_ID INT,
    PRIMARY KEY (Student_ID, Class_ID),
    FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (Class_ID) REFERENCES CLASS(Class_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
	);
    
CREATE TABLE REQUIRES (
	Class_ID INT,
    ISBN VARCHAR(13),
    PRIMARY KEY(Class_ID, ISBN),
    FOREIGN KEY(Class_ID) REFERENCES CLASS(Class_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
		ON DELETE CASCADE
        ON UPDATE CASCADE
	);
    
CREATE TABLE REVIEWS (
	Student_ID VARCHAR(20),
    ISBN VARCHAR(13),
    Out_of_five_stars DECIMAL(2,1) NOT NULL,
    PRIMARY KEY (Student_ID, ISBN),
    FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	CHECK (Out_of_five_stars >= 0 AND Out_of_five_stars <= 5.0)
    );