SELECT Title FROM BOOK, BOOK_GENRE WHERE BOOK.ISBN = BOOK_GENRE.ISBN AND Genre = "Fantasy";

SELECT DISTINCT B.Title, BA.Author, F.Quantity, L.Name FROM BOOK AS B INNER JOIN BOOK_AUTHOR AS BA ON B.ISBN = BA.ISBN 
INNER JOIN FORMAT AS F ON B.ISBN = F.ISBN INNER JOIN LOCATION AS L ON F.Location_ID = L.Location_ID 
WHERE F.Format_type = 'Hardcopy' AND F.Quantity > 8;

SELECT BOOK.Title FROM BOOK, FORMAT WHERE Format_type = 'Hardcopy';

USE library_management;
SELECT * FROM AVAILABLE;

SELECT FORMAT.* FROM FORMAT, BOOK WHERE BOOK.ISBN = FORMAT.ISBN AND BOOK.Title = 'Hamlet';

